name: candidate-dev

services:
  web:
    tty: true
    stdin_open: true
    image: nginx:1.27
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app
    logging:
      options:
        max-size: 512m
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./assets:/app/assets

  server:
    tty: true
    stdin_open: true
    build:
      context: .
      target: dev
    restart: unless-stopped
    volumes:
      - /code/.venv
      - ./:/code
    env_file:
      - .env.dev
    command: poetry run uvicorn --log-level critical --host 0.0.0.0 --port 7000 main:app --reload

  broker:
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - broker_dev:/var/lib/rabbitmq

  db:
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - db_dev:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    env_file:
      - .env.dev

  db-gui:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8081
    env_file:
      - .env.dev
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_ROOT_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_ROOT_PASSWORD
      - ME_CONFIG_MONGODB_URL=mongodb://$DB_USER:$DB_PASSWORD@db:$DB_PORT/$DB_NAME
    links:
      - db
    logging:
      options:
        max-size: 512m
    networks:
      - app

volumes:
  db_dev:
    driver: local
  broker_dev:
    driver: local
