services:
  server:
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    logging:
      options:
        max-size: 1024m
    networks:
      - app

  broker:
    image: rabbitmq:3.13.6
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      options:
        max-size: 512m
    networks:
      - app

  db:
    image: mongo:4.4
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_USERNAME=$DB_USER
      - MONGO_PASSWORD=$DB_PASSWORD
    logging:
      options:
        max-size: 512m
    networks:
      - app

networks:
  app:
    driver: bridge
