name: candidate-registry

services:
  db:
    restart: always
    volumes:
      - db_prod:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_USERNAME=$DB_USER
      - MONGO_PASSWORD=$DB_PASSWORD
    ports:
      - 27017:27017

volumes:
  db_prod:
    driver: local

networks:
  app:
    driver: bridge
