name: candidate-registry

services:
  web:
    tty: true
    image: nginx:1.27
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app
    logging:
      options:
        max-size: 512m
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./assets:/code/assets

  server:
    tty: true
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    build:
      context: .
      target: dev
    restart: unless-stopped
    logging:
      options:
        max-size: 1024m
    volumes:
      - /code/.venv
      - ./:/code
    env_file:
      - .env.dev
    command: poetry run uvicorn --host 0.0.0.0 --port 7000 main:app --reload
    networks:
      - app

  broker:
    tty: true
    image: rabbitmq:3.13.6
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - broker:/var/lib/rabbitmq
    logging:
      options:
        max-size: 512m
    networks:
      - app

  db:
    tty: true
    image: mongo:7.0.13-rc0-jammy
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    volumes:
      - db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    env_file:
      - .env.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_USERNAME=$DB_USER
      - MONGO_PASSWORD=$DB_PASSWORD
    logging:
      options:
        max-size: 512m
    networks:
      - app

  db-gui:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8081
    env_file:
      - .env.dev
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_ROOT_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_ROOT_PASSWORD
      - ME_CONFIG_MONGODB_URL=mongodb://$DB_USER:$DB_PASSWORD@db:$DB_PORT/$DB_NAME
    links:
      - db
    logging:
      options:
        max-size: 512m
    networks:
      - app

volumes:
  db:
    driver: local
  broker:
    driver: local

networks:
  app:
    driver: bridge
